spring.application.name=anyPost

spring.mongodb.uri=${MONGODB_URL}
spring.data.mongodb.auto-index-creation=true


jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

resend.api.key=${RESEND_API_KEY}

management.health.mongodb.enabled=false

